name: armagetronad
version: "daily"
summary: A Tron clone in 3D.
description: |
 Multiplayer lightcycle game. You ride a lightcycle, which leaves a trail of
 pure energy behind it. Crashing into your own trail or that of another player
 is quite fatal. Battle with others for simple kills, for survival, or for
 territorial dominance in the Sumo and Fortress modes.
confinement: devmode

apps:
  armagetronad:
    command: usr/games/armagetronad
    plugs: [opengl, home, x11, network, network-bind]

parts:
  armagetronad:
    source: lp:armagetronad
    plugin: autotools
    build-packages:
      - autotools-dev
      - dh-systemd 
      - imagemagick
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libpng-dev
      - libsdl-image1.2-dev
      - libsdl-mixer1.2-dev
      - libsdl1.2-dev
      - libxml2-dev
      - pkg-config
      - zlib1g-dev
    stage-packages:
      - adduser
      - lsb-base
